### ISSUE TITLE
maybe export instance with conifg argument better than export class and configed in rc 

### ISSUE THREAD

**Issue by axolo** [segemun/sequelize-search-builder#2]
open a entrance for config friendly
easy config builder in app, express, koa and egg.js
easy make a plugin by builder in koa and egg.js
```js
class SequelizeSearchBuilder {
  constuctor (config) {
    // merge defaultConfig
    this.config = config;
  }
}

module.exports = config => new SequelizeSearchBuilder(config);
```

**Comment by segemun** [comment]
Fixed in 77941eeb0fb47ea247328b854046682064b81962

**Comment by segemun** [comment]
README.md has been updated.
You can use setConfig method for redefining configs (not third argument in constructor)

**Comment by axolo** [comment]
https://github.com/axolo/sequelize-query
